FROM python:3.9

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install face-alignment opencv-python-headless imageio[ffmpeg] torch torchvision

CMD ["python", "process_all_videos.py"]
